####### Spring Boot Customized Configuation
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.139.117.24:1433;databaseName=ELNDB_DEV
    username: elnap_user
    password: Newuser1Newuser
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      show-sql: true

###### Java Simplified Encryption ######
jasypt:
  encryptor:
    secret: VFMwMDg1
