####### Spring Boot Customized Configuation
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 
    username:
    password:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
      show-sql: true

###### Java Simplified Encryption ######
jasypt:
  encryptor:
    secret: VFMwMDg1
